// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20230717145421_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Music.Models.Song", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("album")
                        .HasColumnType("TEXT");

                    b.Property<string>("artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("song")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Song");

                    b.HasData(
                        new
                        {
                            id = "song1",
                            album = "Without Warning",
                            artist = "Metro Boomin",
                            name = "Rap Saved Me",
                            song = "21 Savage, Offset & Metro Boomin -  Rap Saved Me  Ft Quavo (Official Audio)"
                        },
                        new
                        {
                            id = "song2",
                            album = "Live.Love.A$AP",
                            artist = "A$AP Rocky",
                            name = "Trilla",
                            song = "A$AP Rocky - Trilla (Ft. A$AP Twelvy & A$AP Nast) [LiveLoveAsap]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
